### ISSUE TITLE
Receiving 'Unexpected error determining zone identifier for MY.DOMAIN.COM: No matching domain found'

### ISSUE THREAD

**Issue by coreyramirezgomez** [bikram990/certbot-dns-dynu#2]
## Input
```certbot certonly --renew-by-default --server https://acme-staging-v02.api.letsencrypt.org/directory -a dns-dynu --dns-dynu-credentials /config/dns-conf/dynu.ini --rsa-key-size 4096 -m [REDACTED]--no-eff-email --agree-tos -d MY.DOMAIN.COM```

## Output

stdout:

> Saving debug log to /var/log/letsencrypt/letsencrypt.log
> Requesting a certificate for MY.DOMAIN.COM
> Unexpected error determining zone identifier for MY.DOMAIN.COM: No matching domain found
> Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

/var/log/letsencrypt/letsencrypt.log:
> 2022-08-10 01:33:24,490:INFO:certbot._internal.auth_handler:Performing the following challenges:
> 2022-08-10 01:33:24,490:INFO:certbot._internal.auth_handler:dns-01 challenge for MY.DOMAIN.COM
> 2022-08-10 01:33:24,491:DEBUG:lexicon.providers.dynu:Request: GET /dns with data None
> 2022-08-10 01:33:24,492:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.dynu.com:443
> 2022-08-10 01:33:25,116:DEBUG:urllib3.connectionpool:https://api.dynu.com:443 "GET /v2/dns HTTP/1.1" 200 822
> 2022-08-10 01:33:25,118:DEBUG:lexicon.providers.dynu:Response: <Response [200]>
> 2022-08-10 01:33:25,119:DEBUG:certbot._internal.error_handler:Encountered exception:
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/certbot/plugins/dns_common_lexicon.py", line 97, in _find_domain_id
>     self.provider.authenticate()
>   File "/usr/lib/python3.9/site-packages/lexicon/providers/base.py", line 74, in authenticate
>     return self._authenticate()
>   File "/usr/lib/python3.9/site-packages/lexicon/providers/dynu.py", line 43, in _authenticate
>     raise Exception("No matching domain found")
> Exception: No matching domain found
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/certbot/_internal/auth_handler.py", line 86, in handle_authorizations
>     resps = self.auth.perform(achalls)
>   File "/usr/lib/python3.9/site-packages/certbot/plugins/dns_common.py", line 76, in perform
>     self._perform(domain, validation_domain_name, validation)
>   File "/usr/lib/python3.9/site-packages/certbot_dns_dynu/dns_dynu.py", line 54, in _perform
>     self._get_dynu_client().add_txt_record(
>   File "/usr/lib/python3.9/site-packages/certbot/plugins/dns_common_lexicon.py", line 47, in add_txt_record
>     self._find_domain_id(domain)
>   File "/usr/lib/python3.9/site-packages/certbot/plugins/dns_common_lexicon.py", line 109, in _find_domain_id
>     raise result2  # pylint: disable=raising-bad-type
> certbot.errors.PluginError: Unexpected error determining zone identifier for MY.DOMAIN.COM: No matching domain found
> 
> 2022-08-10 01:33:25,119:DEBUG:certbot._internal.error_handler:Calling registered functions
> 2022-08-10 01:33:25,119:INFO:certbot._internal.auth_handler:Cleaning up challenges
> 2022-08-10 01:33:25,120:DEBUG:lexicon.providers.dynu:Request: GET /dns with data None
> 2022-08-10 01:33:25,121:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.dynu.com:443
> 2022-08-10 01:33:25,779:DEBUG:urllib3.connectionpool:https://api.dynu.com:443 "GET /v2/dns HTTP/1.1" 200 822
> 2022-08-10 01:33:25,781:DEBUG:lexicon.providers.dynu:Response: <Response [200]>
> 2022-08-10 01:33:25,781:DEBUG:certbot.plugins.dns_common_lexicon:Encountered error finding domain_id during deletion: Unexpected error determining zone identifier for MY.DOMAIN.COM: No matching domain found
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/certbot/plugins/dns_common_lexicon.py", line 97, in _find_domain_id
>     self.provider.authenticate()
>   File "/usr/lib/python3.9/site-packages/lexicon/providers/base.py", line 74, in authenticate
>     return self._authenticate()
>   File "/usr/lib/python3.9/site-packages/lexicon/providers/dynu.py", line 43, in _authenticate
>     raise Exception("No matching domain found")
> Exception: No matching domain found
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/certbot/_internal/auth_handler.py", line 86, in handle_authorizations
>     resps = self.auth.perform(achalls)
>   File "/usr/lib/python3.9/site-packages/certbot/plugins/dns_common.py", line 76, in perform
>     self._perform(domain, validation_domain_name, validation)
>   File "/usr/lib/python3.9/site-packages/certbot_dns_dynu/dns_dynu.py", line 54, in _perform
>     self._get_dynu_client().add_txt_record(
>   File "/usr/lib/python3.9/site-packages/certbot/plugins/dns_common_lexicon.py", line 47, in add_txt_record
>     self._find_domain_id(domain)
>   File "/usr/lib/python3.9/site-packages/certbot/plugins/dns_common_lexicon.py", line 109, in _find_domain_id
>     raise result2  # pylint: disable=raising-bad-type
> certbot.errors.PluginError: Unexpected error determining zone identifier for MY.DOMAIN.COM: No matching domain found
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/certbot/plugins/dns_common_lexicon.py", line 97, in _find_domain_id
>     self.provider.authenticate()
>   File "/usr/lib/python3.9/site-packages/lexicon/providers/base.py", line 74, in authenticate
>     return self._authenticate()
>   File "/usr/lib/python3.9/site-packages/lexicon/providers/dynu.py", line 43, in _authenticate
>     raise Exception("No matching domain found")
> Exception: No matching domain found
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/certbot/plugins/dns_common_lexicon.py", line 65, in del_txt_record
>     self._find_domain_id(domain)
>   File "/usr/lib/python3.9/site-packages/certbot/plugins/dns_common_lexicon.py", line 109, in _find_domain_id
>     raise result2  # pylint: disable=raising-bad-type
> certbot.errors.PluginError: Unexpected error determining zone identifier for MY.DOMAIN.COM: No matching domain found
> 2022-08-10 01:33:25,782:DEBUG:certbot._internal.log:Exiting abnormally:
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/site-packages/certbot/plugins/dns_common_lexicon.py", line 97, in _find_domain_id
>     self.provider.authenticate()
>   File "/usr/lib/python3.9/site-packages/lexicon/providers/base.py", line 74, in authenticate
>     return self._authenticate()
>   File "/usr/lib/python3.9/site-packages/lexicon/providers/dynu.py", line 43, in _authenticate
>     raise Exception("No matching domain found")
> Exception: No matching domain found
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/bin/certbot", line 8, in <module>
>     sys.exit(main())
>   File "/usr/lib/python3.9/site-packages/certbot/main.py", line 19, in main
>     return internal_main.main(cli_args)
>   File "/usr/lib/python3.9/site-packages/certbot/_internal/main.py", line 1744, in main
>     return config.func(config, plugins)
>   File "/usr/lib/python3.9/site-packages/certbot/_internal/main.py", line 1591, in certonly
>     lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
>   File "/usr/lib/python3.9/site-packages/certbot/_internal/main.py", line 141, in _get_and_save_cert
>     lineage = le_client.obtain_and_enroll_certificate(domains, certname)
>   File "/usr/lib/python3.9/site-packages/certbot/_internal/client.py", line 530, in obtain_and_enroll_certificate
>     cert, chain, key, _ = self.obtain_certificate(domains)
>   File "/usr/lib/python3.9/site-packages/certbot/_internal/client.py", line 442, in obtain_certificate
>     orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
>   File "/usr/lib/python3.9/site-packages/certbot/_internal/client.py", line 510, in _get_order_and_authorizations
>     authzr = self.auth_handler.handle_authorizations(orderr, self.config, best_effort)
>   File "/usr/lib/python3.9/site-packages/certbot/_internal/auth_handler.py", line 86, in handle_authorizations
>     resps = self.auth.perform(achalls)
>   File "/usr/lib/python3.9/site-packages/certbot/plugins/dns_common.py", line 76, in perform
>     self._perform(domain, validation_domain_name, validation)
>   File "/usr/lib/python3.9/site-packages/certbot_dns_dynu/dns_dynu.py", line 54, in _perform
>     self._get_dynu_client().add_txt_record(
>   File "/usr/lib/python3.9/site-packages/certbot/plugins/dns_common_lexicon.py", line 47, in add_txt_record
>     self._find_domain_id(domain)
>   File "/usr/lib/python3.9/site-packages/certbot/plugins/dns_common_lexicon.py", line 109, in _find_domain_id
>     raise result2  # pylint: disable=raising-bad-type
> certbot.errors.PluginError: Unexpected error determining zone identifier for MY.DOMAIN.COM: No matching domain found
> 2022-08-10 01:33:25,783:ERROR:certbot._internal.log:Unexpected error determining zone identifier for MY.DOMAIN.COM: No matching domain found

## Environment

OS/container: https://github.com/linuxserver/docker-swag

pip:
```
acme==1.29.0
appdirs==1.4.4
asn1crypto==1.4.0
attrs==22.1.0
azure-common==1.1.28
azure-core==1.25.0
azure-identity==1.10.0
azure-mgmt-core==1.3.1
azure-mgmt-dns==8.0.0
beautifulsoup4==4.11.1
boto3==1.24.48
botocore==1.27.48
bs4==0.0.1
CacheControl==0.12.6
cachetools==5.2.0
certbot==1.29.0
certbot-dns-aliyun==0.38.1
certbot-dns-azure==1.5.0
certbot-dns-cloudflare==1.29.0
certbot-dns-cloudxns==1.29.0
certbot-dns-cpanel==0.4.0
certbot-dns-desec==1.2.0
certbot-dns-digitalocean==1.29.0
certbot-dns-directadmin==0.0.24
certbot-dns-dnsimple==1.29.0
certbot-dns-dnsmadeeasy==1.29.0
certbot-dns-dnspod==0.1.0
certbot-dns-domeneshop==0.2.8
certbot-dns-dynu==0.0.2
certbot-dns-google==1.29.0
certbot-dns-he==1.0.0
certbot-dns-hetzner==1.0.5
certbot-dns-infomaniak==0.1.16
certbot-dns-inwx==2.1.3
certbot-dns-ionos==2022.5.15
certbot-dns-linode==1.29.0
certbot-dns-loopia==1.0.1
certbot-dns-luadns==1.29.0
certbot-dns-netcup==1.1.4
certbot-dns-njalla==1.0.0
certbot-dns-nsone==1.29.0
certbot-dns-ovh==1.29.0
certbot-dns-rfc2136==1.29.0
certbot-dns-route53==1.29.0
certbot-dns-standalone==1.0.3
certbot-dns-transip==0.4.3
certbot-dns-vultr==1.0.3
certbot-plugin-gandi==1.3.2
certifi==2020.12.5
cffi==1.14.5
chardet==4.0.0
charset-normalizer==2.1.0
cloudflare==2.9.11
colorama==0.4.4
ConfigArgParse==1.5.3
configobj==5.0.6
contextlib2==0.6.0
cryptography==3.4.8
distlib==0.3.1
distro==1.5.0
dns-lexicon==3.5.6
dnslib==0.9.20
dnspython==2.2.1
domeneshop==0.4.2
fail2ban==0.11.2
filelock==3.7.1
future==0.18.2
google-api-core==2.8.2
google-api-python-client==2.56.0
google-auth==2.10.0
google-auth-httplib2==0.1.0
googleapis-common-protos==1.56.4
html5lib==1.1
httplib2==0.20.4
idna==3.2
isodate==0.6.1
jmespath==1.0.1
josepy==1.13.0
jsonlines==3.1.0
jsonpickle==2.2.0
lockfile==0.12.2
loopialib==0.2.0
lxml==4.9.1
mock==4.0.3
msal==1.18.0
msal-extensions==1.0.0
msgpack==1.0.2
msrest==0.7.1
oauth2client==4.1.3
oauthlib==3.2.0
ordered-set==4.0.2
packaging==20.9
parsedatetime==2.6
pep517==0.10.0
portalocker==2.5.1
progress==1.5
protobuf==4.21.5
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
PyJWT==2.4.0
pyOpenSSL==21.0.0
pyparsing==2.4.7
pyRFC3339==1.1
python-dateutil==2.8.2
python-digitalocean==1.17.0
python-transip==0.5.0
pytz==2022.1
PyYAML==5.4.1
requests==2.28.1
requests-file==1.5.1
requests-mock==1.9.3
requests-oauthlib==1.3.1
requests-toolbelt==0.9.1
retrying==1.3.3
rsa==4.9
s3transfer==0.6.0
six==1.15.0
soupsieve==2.3.2.post1
tldextract==3.3.1
toml==0.10.2
typing_extensions==4.3.0
uritemplate==4.1.1
urllib3==1.26.5
webencodings==0.5.1
zope.component==5.0.1
zope.event==4.5.0
zope.hookable==5.1.0
zope.interface==5.4.0
```

**Comment by bikram990** [comment]
This should be fixed now. Could you please try the `0.0.3` version and update this issue accordingly?

**Comment by coreyramirezgomez** [comment]
Confirmed working.

Thank you!

stdout (from swag container):
```
Aug 11 21:01:50 blackmesa docker-compose[79840]: Attaching to swag
Aug 11 21:01:52 blackmesa docker-compose[79840]: swag  | s6-rc: info: service s6rc-oneshot-runner: starting
Aug 11 21:01:52 blackmesa docker-compose[79840]: swag  | s6-rc: info: service s6rc-oneshot-runner successfully started
Aug 11 21:01:52 blackmesa docker-compose[79840]: swag  | s6-rc: info: service fix-attrs: starting
Aug 11 21:01:52 blackmesa docker-compose[79840]: swag  | s6-rc: info: service 00-legacy: starting
Aug 11 21:01:52 blackmesa docker-compose[79840]: swag  | s6-rc: info: service 00-legacy successfully started
Aug 11 21:01:52 blackmesa docker-compose[79840]: swag  | s6-rc: info: service fix-attrs successfully started
Aug 11 21:01:52 blackmesa docker-compose[79840]: swag  | s6-rc: info: service legacy-cont-init: starting
Aug 11 21:01:52 blackmesa docker-compose[79840]: swag  | cont-init: info: running /etc/cont-init.d/01-envfile
Aug 11 21:01:52 blackmesa docker-compose[79840]: swag  | cont-init: info: /etc/cont-init.d/01-envfile exited 0
Aug 11 21:01:52 blackmesa docker-compose[79840]: swag  | cont-init: info: running /etc/cont-init.d/02-tamper-check
Aug 11 21:01:52 blackmesa docker-compose[79840]: swag  | cont-init: info: /etc/cont-init.d/02-tamper-check exited 0
Aug 11 21:01:52 blackmesa docker-compose[79840]: swag  | cont-init: info: running /etc/cont-init.d/10-adduser
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  |
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | -------------------------------------
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  |           _         ()
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  |          | |  ___   _    __
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  |          | | / __| | |  /  \
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  |          | | \__ \ | | | () |
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  |          |_| |___/ |_|  \__/
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  |
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  |
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | Brought to you by linuxserver.io
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | -------------------------------------
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  |
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | To support the app dev(s) visit:
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | Certbot: https://supporters.eff.org/donate/support-work-on-certbot
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  |
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | To support LSIO projects visit:
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | https://www.linuxserver.io/donate/
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | -------------------------------------
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | GID/UID
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | -------------------------------------
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  |
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | User uid:    1000
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | User gid:    1000
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | -------------------------------------
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  |
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | cont-init: info: /etc/cont-init.d/10-adduser exited 0
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | cont-init: info: running /etc/cont-init.d/20-config
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | cont-init: info: /etc/cont-init.d/20-config exited 0
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | cont-init: info: running /etc/cont-init.d/30-keygen
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | using keys found in /config/keys
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | cont-init: info: /etc/cont-init.d/30-keygen exited 0
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | cont-init: info: running /etc/cont-init.d/50-config
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | Variables set:
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | PUID=1000
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | PGID=1000
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | TZ=America/Los_Angeles
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | URL=DOMAIN
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | SUBDOMAINS=test
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | EXTRA_DOMAINS=
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | ONLY_SUBDOMAINS=true
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | VALIDATION=dns
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | CERTPROVIDER=
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | DNSPLUGIN=dynu
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | EMAIL=[REDACTED]
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | STAGING=true
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  |
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | NOTICE: Staging is active
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | Using Let's Encrypt as the cert provider
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | SUBDOMAINS entered, processing
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | SUBDOMAINS entered, processing
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | Only subdomains, no URL in cert
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | Sub-domains processed are:  -d test.DOMAIN
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | E-mail address entered: [REDACTED]
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | dns validation via dynu plugin is selected
Aug 11 21:01:53 blackmesa docker-compose[79840]: swag  | Generating new certificate
Aug 11 21:01:57 blackmesa docker-compose[79840]: swag  | Saving debug log to /var/log/letsencrypt/letsencrypt.log
Aug 11 21:01:57 blackmesa docker-compose[79840]: swag  | Requesting a certificate for test.DOMAIN
Aug 11 21:02:00 blackmesa docker-compose[79840]: swag  | Waiting 120 seconds for DNS changes to propagate
Aug 11 21:04:12 blackmesa docker-compose[79840]: swag  |
Aug 11 21:04:12 blackmesa docker-compose[79840]: swag  | Successfully received certificate.
Aug 11 21:04:12 blackmesa docker-compose[79840]: swag  | Certificate is saved at: /etc/letsencrypt/live/test.DOMAIN/fullchain.pem
Aug 11 21:04:12 blackmesa docker-compose[79840]: swag  | Key is saved at:         /etc/letsencrypt/live/test.DOMAIN/privkey.pem
Aug 11 21:04:12 blackmesa docker-compose[79840]: swag  | This certificate expires on 2022-11-09.
Aug 11 21:04:12 blackmesa docker-compose[79840]: swag  | These files will be updated when the certificate renews.
Aug 11 21:04:12 blackmesa docker-compose[79840]: swag  | NEXT STEPS:
Aug 11 21:04:12 blackmesa docker-compose[79840]: swag  | - The certificate will need to be renewed before it expires. Certbot can automatically renew the certificate in the background, but you may need to take steps to enable that functionality. See https://certbot.org/renewal-setup for instructions.
Aug 11 21:04:12 blackmesa docker-compose[79840]: swag  |
Aug 11 21:04:12 blackmesa docker-compose[79840]: swag  | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Aug 11 21:04:12 blackmesa docker-compose[79840]: swag  | If you like Certbot, please consider supporting our work by:
Aug 11 21:04:12 blackmesa docker-compose[79840]: swag  |  * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
Aug 11 21:04:12 blackmesa docker-compose[79840]: swag  |  * Donating to EFF:                    https://eff.org/donate-le
Aug 11 21:04:12 blackmesa docker-compose[79840]: swag  | - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Aug 11 21:04:13 blackmesa docker-compose[79840]: swag  | New certificate generated; starting nginx
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | cont-init: info: /etc/cont-init.d/50-config exited 0
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | cont-init: info: running /etc/cont-init.d/60-renew
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | The cert does not expire within the next day. Letting the cron script handle the renewal attempts overnight (2:08am).
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | cont-init: info: /etc/cont-init.d/60-renew exited 0
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | cont-init: info: running /etc/cont-init.d/70-templates
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | cont-init: info: /etc/cont-init.d/70-templates exited 0
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | cont-init: info: running /etc/cont-init.d/90-custom-folders
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | cont-init: info: /etc/cont-init.d/90-custom-folders exited 0
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | cont-init: info: running /etc/cont-init.d/99-custom-files
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | [custom-init] no custom files found exiting...
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | cont-init: info: /etc/cont-init.d/99-custom-files exited 0
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | s6-rc: info: service legacy-cont-init successfully started
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | s6-rc: info: service init-mods: starting
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | s6-rc: info: service init-mods successfully started
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | s6-rc: info: service init-mods-package-install: starting
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | s6-rc: info: service init-mods-package-install successfully started
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | s6-rc: info: service init-mods-end: starting
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | s6-rc: info: service init-mods-end successfully started
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | s6-rc: info: service init-services: starting
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | s6-rc: info: service init-services successfully started
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | s6-rc: info: service legacy-services: starting
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | services-up: info: copying legacy longrun cron (no readiness notification)
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | services-up: info: copying legacy longrun fail2ban (no readiness notification)
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | services-up: info: copying legacy longrun nginx (no readiness notification)
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | services-up: info: copying legacy longrun php-fpm (no readiness notification)
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | s6-rc: info: service legacy-services successfully started
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | s6-rc: info: service 99-ci-service-check: starting
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | [ls.io-init] done.
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | s6-rc: info: service 99-ci-service-check successfully started
Aug 11 21:04:14 blackmesa docker-compose[79840]: swag  | Server ready
```
